# -*- coding: utf-8 -*-
"""sugarcane_segformer_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V3p9oP7sG37QQ86ac3-aHabUgnEf33W0

# Fine-Tuning SegFormer para Detección de Caña de Azúcar (Sentinel-2)

Fine-Tuning SegFormer (MIT-B3) para segmentacion de cana de azucar con Sentinel-2.

Clases: 0 = background | 1 = sugar_cane
Color mascara CVAT: verde RGB(88, 207, 74) = cana, negro = background

# 0. Instalacion de dependencias
"""

# Cell 1: Instalacion de dependencias
!pip install -q datasets transformers evaluate torch torchvision pillow matplotlib opencv-python albumentations
print("Dependencias instaladas")

# import importlib.metadata as md

# libs = {
#     "transformers (Hugging Face)": "transformers",
#     "rasterio":                "rasterio",
#     "OpenCV (cv2)":            "opencv-python",
#     "PyTorch (torch)":         "torch",
#     "albumentations":          "albumentations",
#     "NumPy":                   "numpy",
#     "Matplotlib":              "matplotlib",
#     "earthengine-api (GEE)":   "earthengine-api",
#     "geemap":                  "geemap",
# }

# print("=== Versiones de librerías ===")
# for nombre, pkg in libs.items():
#     try:
#         print(f"{nombre:<28} {md.version(pkg)}")
#     except Exception:
#         print(f"{nombre:<28} (no detectada: {pkg})")

# try:
#     import platform, torch
#     print(f"{'Python':<28} {platform.python_version()}")
#     print(f"{'CUDA (torch)':<28} {torch.version.cuda}")
#     print(f"{'GPU':<28} {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'sin GPU / CPU'}")
# except Exception as e:
#     print("Python/CUDA:", e)

"""# 1. Estructura de carpetas en Drive

Antes de ejecutar, creá esta estructura en tu Drive:
```
MiDrive/
└── sugarcane/
    ├── images/           <- tiles .jpg (Sentinel-2 RGB de los 3 distritos)
    ├── masks/            <- mascaras .png (exportacion CVAT Segmentation Mask 1.1)
    └── test_images/      <- (opcional) imagenes sueltas para inferencia rapida
```
Montar Drive y definir rutas
"""

from google.colab import drive
drive.mount('/content/drive')

# CAMBIA ESTO si tus carpetas estan en otra ruta
BASE_DIR = "/content/drive/MyDrive/sugarcane"
IMAGE_DIR = BASE_DIR + "/images"
MASK_DIR = BASE_DIR + "/masks"
#SAN_SALVADOR_DIR = BASE_DIR + "/san_salvador"  # para validacion externa (mas adelante)

import os
print(f"Imagenes: {IMAGE_DIR}")
print(f"Mascaras: {MASK_DIR}")
#print(f"San Salvador: {SAN_SALVADOR_DIR}")

img_count = len(os.listdir(IMAGE_DIR)) if os.path.isdir(IMAGE_DIR) else 0
mask_count = len(os.listdir(MASK_DIR)) if os.path.isdir(MASK_DIR) else 0
print(f"Imagenes encontradas: {img_count}")
print(f"Mascaras encontradas: {mask_count}")

"""# 2.  Funcion compartida para convertir mascaras RGB -> clases

Cada imagen se vincula con su máscara por nombre de archivo.
Las máscaras CVAT usan colores RGB → se convierten a índices de clase.
"""

# ============================================================
# Color cana: RGB(88, 207, 74). Deteccion robusta:
#   - G > 100: capta el verde (88,207,74) tiene G=207; (0,255,0) tiene G=255.
#   - R < 150 y B < 150: excluye rojos, amarillos, azules, cianes.
#   - Funciona para (88,207,74), (0,255,0) y cualquier verde razonable de CVAT.
# ============================================================
import numpy as np

def mask_rgb_to_class(mask_rgb):
    """Convierte mascara RGB a indices de clase: 0=background, 1=sugar_cane.

    Args:
        mask_rgb: numpy array (H, W, 3) en formato RGB.
    Returns:
        numpy array (H, W) int64 con valores 0 (background) o 1 (sugar_cane).
    """
    r, g, b = mask_rgb[:, :, 0], mask_rgb[:, :, 1], mask_rgb[:, :, 2]
    sugar_cane = (g > 100) & (r < 150) & (b < 150)
    out = np.zeros(mask_rgb.shape[:2], dtype=np.int64)
    out[sugar_cane] = 1
    return out

"""# 3. Dataset personalizado (con augmentacion opcional)"""

import os, cv2
import numpy as np
from torch.utils.data import Dataset
from glob import glob
import albumentations as A

class SugarCaneDataset(Dataset):
    """Lee imagenes .jpg + mascaras .png y las matchea por nombre de archivo.

    Args:
        image_dir: carpeta con imagenes .jpg
        mask_dir: carpeta con mascaras .png
        augment: si True, aplica data augmentation (solo para train)
    """
    def __init__(self, image_dir, mask_dir, augment=False):
        self.image_dir = image_dir
        self.augment = augment

        # Matchear mascaras con imagenes por nombre (sin extension)
        mask_paths = sorted(glob(os.path.join(mask_dir, "*.png")))
        self.samples = []

        for mask_path in mask_paths:
            name = os.path.basename(mask_path)
            img_name = name.replace(".png", ".jpg")
            img_path = os.path.join(image_dir, img_name)
            if os.path.exists(img_path):
                self.samples.append((img_path, mask_path))

        print(f"Pares imagen-mascara cargados: {len(self.samples)}")

        # Augmentacion solo espacial + color jitter (la mascara se transforma espacialmente)
        if augment:
            self.transform = A.Compose([
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.5),
                A.RandomRotate90(p=0.5),
                A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.3),
            ])
        else:
            self.transform = None

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, mask_path = self.samples[idx]

        # Leer imagen (BGR -> RGB)
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Leer mascara (BGR -> RGB -> clases)
        mask_rgb = cv2.imread(mask_path)
        mask_rgb = cv2.cvtColor(mask_rgb, cv2.COLOR_BGR2RGB)
        mask = mask_rgb_to_class(mask_rgb)  # funcion compartida

         # Aplicar augmentacion (solo train)
        if self.transform:
            augmented = self.transform(image=image, mask=mask)
            image = augmented['image']
            mask = augmented['mask']

        return {"pixel_values": image, "label": mask}

# Verificar que el dataset carga correctamente
dataset = SugarCaneDataset(IMAGE_DIR, MASK_DIR)
s = dataset[0]
print(f"Imagen: {s['pixel_values'].shape}")
print(f"Mascara: {s['label'].shape}, clases: {np.unique(s['label'])}")

# Mostrar una muestra
import matplotlib.pyplot as plt
fig, axes = plt.subplots(1, 2, figsize=(10, 5))
axes[0].imshow(s['pixel_values'])
axes[0].set_title("Imagen"); axes[0].axis('off')
axes[1].imshow(s['label'], cmap='viridis')
axes[1].set_title(f"Mascara (clases: {np.unique(s['label'])})"); axes[1].axis('off')
plt.show()

"""# 4. Diagnostico de colores en mascaras"""

# ============================================================
# Confirmar que colores tiene realmente tu mascara CVAT.
# Deberias ver: negro (0,0,0) = background y verde (88,207,74) = sugar_cane.
# Si ves otros colores, ajusta mask_rgb_to_class en Cell 3.
# ============================================================
def diagnose_mask_colors(mask_dir, num_samples=3):
    mask_paths = sorted(glob(os.path.join(mask_dir, '*.png')))[:num_samples]
    print(f'Analizando {len(mask_paths)} mascaras...\n')
    for mp in mask_paths:
        mask_bgr = cv2.imread(mp)
        mask_rgb = cv2.cvtColor(mask_bgr, cv2.COLOR_BGR2RGB)
        pixels = mask_rgb.reshape(-1, 3)
        unique_colors = np.unique(pixels, axis=0)
        print(f'{os.path.basename(mp)}:')
        print(f'   Colores unicos: {len(unique_colors)}')
        for color in unique_colors[:10]:
            count = np.sum(np.all(pixels == color, axis=1))
            print(f'   - RGB{tuple(color)}: {count} pixeles')
        print()

diagnose_mask_colors(MASK_DIR, num_samples=3)

"""# 5. Split 70/15/15 (train / val / test)"""

# ============================================================
# 513 imagenes -> 359 train / 76 val / 78 test
# El test set NUNCA se usa durante entrenamiento. Se evalua al final.
# ============================================================
import torch
from torch.utils.data import random_split

torch.manual_seed(42)
total = len(dataset)
train_size = int(0.70 * total)
val_size = int(0.15 * total)
test_size = total - train_size - val_size

train_raw, val_raw, test_raw = random_split(dataset, [train_size, val_size, test_size])
print(f"Train: {len(train_raw)} | Val: {len(val_raw)} | Test: {len(test_raw)}")

"""# 6.  Procesador SegFormer + adaptador HF + collate_fn"""

from transformers import SegformerImageProcessor

labels = ["background", "sugar_cane"]
id2label = {0: "background", 1: "sugar_cane"}
label2id = {"background": 0, "sugar_cane": 1}

model_checkpoint = "nvidia/segformer-b3-finetuned-ade-512-512"

image_processor = SegformerImageProcessor.from_pretrained(
    model_checkpoint,
    reduce_labels=False
)

class HFDatasetAdapter(Dataset):
    """Adapta torch Dataset -> HuggingFace Trainer.
    Aplica image_processor (resize 512x512 + normalizacion ImageNet) a cada muestra.
    """
    def __init__(self, subset, image_processor, augment=False):
        self.subset = subset
        self.image_processor = image_processor
        self.augment = augment

        if augment:
            self.transform = A.Compose([
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.5),
                A.RandomRotate90(p=0.5),
                A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.3),
            ])
        else:
            self.transform = None

    def __len__(self):
        return len(self.subset)

    def __getitem__(self, idx):
        item = self.subset[idx]
        image = item["pixel_values"]
        mask = item["label"]

        # Augmentacion antes del image_processor
        if self.transform:
            augmented = self.transform(image=image, mask=mask)
            image = augmented['image']
            mask = augmented['mask']

        # image_processor: resize 512x512 + normalizacion
        batch = self.image_processor(
            [image], [mask],
            return_tensors="pt"
        )
        return {
            "pixel_values": batch["pixel_values"].squeeze(0),
            "labels": batch["labels"].squeeze(0),
        }

# collate_fn explicito: apila tensores en batch
def collate_fn(batch):
    return {
        "pixel_values": torch.stack([item["pixel_values"] for item in batch]),
        "labels": torch.stack([item["labels"] for item in batch]),
    }

# Train CON augmentacion, val y test SIN augmentacion
train_ds = HFDatasetAdapter(train_raw, image_processor, augment=True)
val_ds = HFDatasetAdapter(val_raw, image_processor, augment=False)
test_ds = HFDatasetAdapter(test_raw, image_processor, augment=False)

print(f"Train: {len(train_ds)} | Val: {len(val_ds)} | Test: {len(test_ds)}")
s = train_ds[0]
print(f"pixel_values: {s['pixel_values'].shape}, labels: {s['labels'].shape}")
print(f"Clases en labels: {torch.unique(s['labels']).tolist()}")

"""# 7. Cargar modelo SegFormer MIT-B3"""

from transformers import SegformerForSemanticSegmentation
import torch

model = SegformerForSemanticSegmentation.from_pretrained(
    model_checkpoint,
    num_labels=2,
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True,  # necesario: el checkpoint tiene 150 clases (ADE20k), nosotros 2
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
print(f"Modelo en {device}")

p = sum(p.numel() for p in model.parameters())
print(f"Parametros: {p:,}")

"""# 8: Metricas (mean IoU)"""

import evaluate
import torch.nn as nn

metric = evaluate.load("mean_iou")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    logits_t = torch.from_numpy(logits)
    labels_t = torch.from_numpy(labels)

    # Logits vienen a 1/4 de resolucion. Upscalear a tamaño del label.
    logits_t = nn.functional.interpolate(
        logits_t, size=labels_t.shape[-2:], mode="bilinear", align_corners=False
    ).argmax(dim=1)

    preds = logits_t.cpu().numpy()
    m = metric.compute(
        predictions=preds,
        references=labels,
        num_labels=2,
        ignore_index=255,
        reduce_labels=False  # consistente con el image_processor
    )
    # Quitar metricas por categoria para limpiar logs
    m.pop("per_category_accuracy", None)
    m.pop("per_category_iou", None)
    return m

print("mean_iou configurado (ignore_index=255, 2 clases, reduce_labels=False)")

"""# 9. TrainingArguments + Early Stopping + Trainer"""

from transformers import TrainingArguments, Trainer, EarlyStoppingCallback

RUN_LABEL = "run12_steps200_pat30_epochs500"
EVAL_STEPS = 200
PATIENCE = 30
TRAIN_EPOCHS = 500


training_args = TrainingArguments(
    # ── OUTPUT
    output_dir=f"segformer-sugarcane-{RUN_LABEL}",        # REQUERIDO. Carpeta donde se guardan checkpoints, logs y modelo final.
    report_to="none",                        # OPCIONAL. "none" desactiva logging en WandB/MLflow/TensorBoard. Sin esto, Trainer intenta loguear a plataformas externas.

    # ── OPTIMIZADOR
    learning_rate=6e-5,                      # OPCIONAL (default 5e-5). Tasa de aprendizaje. Bajo para fine-tuning: muy alto → catastrophic forgetting, muy bajo → no converge.
    max_grad_norm=1.0,                       # OPCIONAL (default 1.0). Gradient clipping. Si la norma del gradiente supera 1.0, se escala hacia abajo. Previene exploding gradients.
    warmup_steps=50,                         # OPCIONAL (default 0). Primeros 50 pasos: el lr sube linealmente de 0 a 6e-5. Después decae linealmente a 0. Evita sacudida al inicio del fine-tuning.

    # ── ÉPOCAS Y BATCH
    num_train_epochs=TRAIN_EPOCHS,                    # OPCIONAL (default 3). Máximo de épocas. Como hay early stopping, casi nunca llega a 100. Es un techo de seguridad.
    per_device_train_batch_size=2,           # OPCIONAL (default 8). Imágenes por GPU en entrenamiento. Limitado por VRAM de la T4 (16 GB) con MiT-B3 a 512×512.
    per_device_eval_batch_size=4,            # OPCIONAL (default 8). Imágenes por GPU en evaluación. Puede ser mayor que train porque no guarda gradientes (menos memoria).
    gradient_accumulation_steps=4,           # OPCIONAL (default 1). Acumula gradientes de 4 mini-batches antes de hacer un paso de optimización. Batch efectivo = 2×4 = 8. Simula batch grande sin más memoria.

    # ── EVALUACIÓN Y GUARDADO
    eval_strategy="steps",                  # OPCIONAL (default "no"). "steps" = evalúa cada N pasos (definido por eval_steps). En transformers <4.46 se llama "evaluation_strategy".
    eval_steps=EVAL_STEPS,                           # NECESARIO si eval_strategy="steps". Frecuencia de evaluación en validación. Cada 50 pasos evalúa mIoU en val_ds.
    save_strategy="steps",                   # OPCIONAL (default "steps"). "steps" = guarda checkpoint cada N pasos. Debe coincidir con eval_steps para que load_best_model_at_end funcione.
    save_steps=EVAL_STEPS,                           # NECESARIO si save_strategy="steps". Frecuencia de guardado de checkpoints. Igual a eval_steps para que cada eval tenga su checkpoint.
    save_total_limit=3,                      # OPCIONAL (default None = sin límite). Mantiene solo los 3 mejores checkpoints en disco. Borra los demás para no llenar Drive/Colab.
    load_best_model_at_end=True,             # OPCIONAL (default False). Al terminar, carga el checkpoint con mejor mIoU de validación (no necesariamente el último). Requiere save_strategy="steps".

    # ── MÉTRICA DE SELECCIÓN
    metric_for_best_model="mean_iou",        # OPCIONAL (default "loss"). Métrica usada para seleccionar el mejor checkpoint. Debe coincidir con una key que devuelve compute_metrics.
    greater_is_better=True,                 # OPCIONAL (default None). True porque mIoU más alto = mejor. Si fuera "loss", sería False.

    # ── LOGGING
    logging_steps=10,                       # OPCIONAL (default 500). Imprime métricas en consola cada 10 pasos (train loss, lr, etc.).

    # ── RENDIMIENTO
    fp16=True,                               # OPCIONAL (default False). Precisión mixta: float16 en forward/backward, float32 en master weights. Reduce memoria ~40% y acelera en T4. Sin impacto en convergencia.
    dataloader_num_workers=2,                # OPCIONAL (default 0). Procesos paralelos para cargar datos del disco. 0 = carga en el proceso principal (lento). 2 es conservador para Colab.

    # ── DATASET
    remove_unused_columns=False,             # OPCIONAL (default True). Por defecto Trainer elimina columnas del dataset que no matchean la firma del modelo. Como usamos dataset custom (diccionario pixel_values + labels), hay que desactivarlo para que no rompa.

    # ── REPRODUCIBILIDAD
    seed=42,                                 # OPCIONAL (default 42). Semilla para shuffle de datos, init de pesos no pre-entrenados y dropout. Si cambia, los resultados varían levemente.

    # ── HUB
    push_to_hub=False,                       # OPCIONAL (default False). Si True, sube el modelo a Hugging Face Hub al terminar. False = no subir.
)

trainer = Trainer(
    model=model,                             # REQUERIDO. Modelo PyTorch (SegformerForSemanticSegmentation). Debe estar ya instanciado con num_labels=2 e ignore_mismatched_sizes=True.
    args=training_args,                     # REQUERIDO. Objeto TrainingArguments configurado arriba.
    train_dataset=train_ds,                 # REQUERIDO. Dataset de entrenamiento (359 imgs). Debe devolver dict con "pixel_values" y "labels".
    eval_dataset=val_ds,                     # REQUERIDO. Dataset de validación (76 imgs). Se usa para eval_steps y para early stopping.
    compute_metrics=compute_metrics,        # OPCIONAL pero recomendado. Función que recibe (logits, labels) y devuelve dict con métricas. Sin esto, Trainer solo loguea loss.
    data_collator=collate_fn,               # OPCIONAL pero recomendado. Función que arma los batches. Aquí: torch.stack de pixel_values y labels. Sin esto, Trainer usa default que puede no respetar el formato del dataset custom.
    callbacks=[EarlyStoppingCallback(early_stopping_patience=PATIENCE)],  # OPCIONAL. Detiene el entrenamiento si mIoU no mejora en 50 evaluaciones consecutivas. Con eval_steps=50 → hasta 2.500 pasos sin mejora antes de frenar.
)

print("Trainer listo con Early Stopping")

"""# 10. Entrenar"""

trainer.train()

"""## 10.1 Evaluar en val y test."""

val_metrics = trainer.evaluate(val_ds)
test_metrics = trainer.evaluate(test_ds)

"""# 11. Guardar modelo en drive"""

SAVE_PATH = "/content/drive/MyDrive/sugarcane/segformer-sugarcane-final"
trainer.save_model(SAVE_PATH)
image_processor.save_pretrained(SAVE_PATH)
print(f"Modelo guardado en: {SAVE_PATH}")
!ls -lh "{SAVE_PATH}"

"""# 12. Visualizar curvas de entrenamiento"""

import matplotlib.pyplot as plt

log_history = trainer.state.log_history

# Extraer datos de loss y mIoU
train_loss = [(x["step"], x["loss"]) for x in log_history if "loss" in x]
eval_loss = [(x["step"], x["eval_loss"]) for x in log_history if "eval_loss" in x]
eval_miou = [(x["step"], x["eval_mean_iou"]) for x in log_history if "eval_mean_iou" in x]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Loss
if train_loss:
    axes[0].plot([x[0] for x in train_loss], [x[1] for x in train_loss], label="Train loss", alpha=0.7)
if eval_loss:
    axes[0].plot([x[0] for x in eval_loss], [x[1] for x in eval_loss], label="Val loss", marker='o', markersize=3)
axes[0].set_xlabel("Step"); axes[0].set_ylabel("Loss"); axes[0].set_title("Curva de perdida")
axes[0].legend(); axes[0].grid(True, alpha=0.3)

# mIoU
if eval_miou:
    axes[1].plot([x[0] for x in eval_miou], [x[1] for x in eval_miou], label="Val mIoU", marker='o', color='green')
    axes[1].axhline(y=0.85, color='red', linestyle='--', label="Hipotesis (0.85)")
axes[1].set_xlabel("Step"); axes[1].set_ylabel("mean IoU"); axes[1].set_title("mIoU en validacion")
axes[1].legend(); axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/sugarcane/training_curves.png", dpi=150, bbox_inches="tight")
plt.show()
print("Curvas guardadas en: /content/drive/MyDrive/sugarcane/training_curves.png")

"""# 13. Cargar modelo entrenado + procesador"""

import torch
from transformers import SegformerForSemanticSegmentation, SegformerImageProcessor
import numpy as np
import matplotlib.pyplot as plt
import cv2

MODEL_PATH = "/content/drive/MyDrive/sugarcane/segformer-sugarcane-final"

model = SegformerForSemanticSegmentation.from_pretrained(MODEL_PATH)
image_processor = SegformerImageProcessor.from_pretrained(MODEL_PATH)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
model.eval()
print(f"Modelo cargado desde {MODEL_PATH}")

"""# 14. Funcion de inferencia + visualizacion"""

# ============================================================
# Usa mask_rgb_to_class() (la MISMA funcion del dataset)
# para leer el ground truth. Antes usaba R<50,G>100,B<50 que NO detecta
# el color RGB(88,207,74) porque R=88>50 y B=74>50.
# ============================================================

def predict_and_show(image_path, mask_path=None, save_path=None):
    """Ejecuta inferencia sobre una imagen y muestra resultado lado a lado."""
    img_bgr = cv2.imread(image_path)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    inputs = image_processor(images=img_rgb, return_tensors="pt").to(device)

    with torch.no_grad():
        logits = model(pixel_values=inputs["pixel_values"]).logits

    # Upscalear a tamaño original
    logits_upsampled = torch.nn.functional.interpolate(
        logits, size=img_rgb.shape[:2], mode="bilinear", align_corners=False
    )
    pred_mask = logits_upsampled.argmax(dim=1).squeeze(0).cpu().numpy()

    # Overlay: verde donde predice sugar_cane
    overlay = img_rgb.copy()
    overlay[pred_mask == 1] = [0, 200, 0]

    n_cols = 4 if mask_path else 3
    fig, axes = plt.subplots(1, n_cols, figsize=(5 * n_cols, 5))

    axes[0].imshow(img_rgb)
    axes[0].set_title("Imagen original"); axes[0].axis("off")

    axes[1].imshow(pred_mask, cmap="viridis", vmin=0, vmax=1)
    axes[1].set_title(f"Prediccion\n(cana: {(pred_mask==1).sum():,} px)"); axes[1].axis("off")

    axes[2].imshow(overlay)
    axes[2].set_title("Overlay (verde = cana)"); axes[2].axis("off")

    if mask_path:
        # CORRECCION: usar mask_rgb_to_class (funcion compartida) en vez de umbrales inline
        gt_bgr = cv2.imread(mask_path)
        gt_rgb = cv2.cvtColor(gt_bgr, cv2.COLOR_BGR2RGB)
        gt_class = mask_rgb_to_class(gt_rgb)

        axes[3].imshow(gt_class, cmap="viridis", vmin=0, vmax=1)
        axes[3].set_title(f"Ground truth\n(cana: {(gt_class==1).sum():,} px)"); axes[3].axis("off")

        # IoU de esta imagen
        intersection = ((pred_mask == 1) & (gt_class == 1)).sum()
        union = ((pred_mask == 1) | (gt_class == 1)).sum()
        iou = intersection / union if union > 0 else 0
        fig.suptitle(f"IoU cana: {iou:.3f}", fontsize=14)

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    return pred_mask

"""# 15. Probar con 3 imagenes al azar del val set"""

import random

val_indices = list(range(len(val_raw)))
random.seed(42)
test_idxs = random.sample(val_indices, min(3, len(val_indices)))

for idx in test_idxs:
    img_path = dataset.samples[val_raw.indices[idx]][0]
    mask_path = dataset.samples[val_raw.indices[idx]][1]

    print(f"\n{'='*60}")
    print(f"Muestra #{idx} - {os.path.basename(img_path)}")
    predict_and_show(img_path, mask_path)

"""# 16. IoU promedio en todo el validation set"""

from tqdm.notebook import tqdm

def evaluate_set(subset, dataset, image_processor, model, device, set_name="val"):
    """Evalua IoU sobre un subset (val o test) del dataset."""
    ious = []
    for idx in tqdm(range(len(subset)), desc=f"Evaluando {set_name} set"):
        img_path = dataset.samples[subset.indices[idx]][0]
        mask_path = dataset.samples[subset.indices[idx]][1]

        img_bgr = cv2.imread(img_path)
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

        inputs = image_processor(images=img_rgb, return_tensors="pt").to(device)
        with torch.no_grad():
            logits = model(pixel_values=inputs["pixel_values"]).logits

        logits_up = torch.nn.functional.interpolate(
            logits, size=img_rgb.shape[:2], mode="bilinear", align_corners=False
        )
        pred = logits_up.argmax(dim=1).squeeze(0).cpu().numpy()

        # CORRECCION: mask_rgb_to_class en vez de umbrales inline
        gt_bgr = cv2.imread(mask_path)
        gt_rgb = cv2.cvtColor(gt_bgr, cv2.COLOR_BGR2RGB)
        gt_class = mask_rgb_to_class(gt_rgb)

        inter = ((pred == 1) & (gt_class == 1)).sum()
        union = ((pred == 1) | (gt_class == 1)).sum()
        ious.append(inter / union if union > 0 else 0)

    ious = np.array(ious)
    print(f"\nMetricas en {set_name} set ({len(ious)} muestras):")
    print(f"   Mean IoU (cana): {ious.mean():.4f}")
    print(f"   Median IoU:      {np.median(ious):.4f}")
    print(f"   Std:             {ious.std():.4f}")
    print(f"   Min:             {ious.min():.4f}")
    print(f"   Max:             {ious.max():.4f}")
    return ious

# Evaluar validation set
val_ious = evaluate_set(val_raw, dataset, image_processor, model, device, "val")

# Histograma
plt.figure(figsize=(8, 4))
plt.hist(val_ious, bins=10, edgecolor="black", alpha=0.7)
plt.xlabel("IoU (cana)"); plt.ylabel("Frecuencia")
plt.title("Distribucion de IoU en validation set")
plt.axvline(val_ious.mean(), color="red", linestyle="--", label=f"Media: {val_ious.mean():.3f}")
plt.legend(); plt.show()

"""# 17. Evaluacion final en TEST set (nunca visto en entrenamiento)"""

# ============================================================
# El test set (77 imagenes) nunca se uso durante entrenamiento.
# Estas son las metricas finales que van al Capitulo 4 de la tesis.
# ============================================================
test_ious = evaluate_set(test_raw, dataset, image_processor, model, device, "test")

plt.figure(figsize=(8, 4))
plt.hist(test_ious, bins=10, edgecolor="black", alpha=0.7, color="orange")
plt.xlabel("IoU (cana)"); plt.ylabel("Frecuencia")
plt.title("Distribucion de IoU en TEST set")
plt.axvline(test_ious.mean(), color="red", linestyle="--", label=f"Media: {test_ious.mean():.3f}")
plt.axvline(0.85, color="blue", linestyle="--", label="Hipotesis (0.85)")
plt.legend(); plt.show()

print(f"\n{'='*60}")
print(f"RESULTADO FINAL:")
print(f"  Val  mIoU: {val_ious.mean():.4f}")
print(f"  Test mIoU: {test_ious.mean():.4f}")
print(f"  Hipotesis: 0.85")
if test_ious.mean() >= 0.85:
    print(f"  >>> HIPOTESIS SUPERADA en test set <<<")
else:
    print(f"  >>> Hipotesis NO superada en test set <<<")
print(f"{'='*60}")

"""# Celda 18: Generar figura de aumento de datos para la tesis
Grid 2x5: fila arriba = imagenes, fila abajo = mascaras
"""

import albumentations as A
import matplotlib.pyplot as plt
import cv2
import numpy as np

# Elegir una tesela que tenga caña visible (cambiar índice si hace falta)
SAMPLE_IDX = 0
img_path, mask_path = dataset.samples[SAMPLE_IDX]

#Leer imagen y mascara en RGB
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
mask_rgb = cv2.imread(mask_path)
mask_rgb = cv2.cvtColor(mask_rgb, cv2.COLOR_BGR2RGB)
mask_class = mask_rgb_to_class(mask_rgb)

#Definir las 5 transformaciones (p=1.0 para que siempre se apliquen)
transforms = [
    ("Original",              A.Compose([])),
    ("HorizontalFlip",        A.HorizontalFlip(p=1.0)),
    ("VerticalFlip",          A.VerticalFlip(p=1.0)),
    ("RandomRotate90",        A.RandomRotate90(p=1.0)),
    ("BrightnessContrast",    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=1.0)),
]

fig, axes = plt.subplots(2, 5, figsize=(15, 6))

for col, (name, tfm) in enumerate(transforms):
    augmented = tfm(image=img, mask=mask_class)
    aug_img = augmented["image"]
    aug_mask = augmented["mask"]

    axes[0, col].imshow(aug_img)
    axes[0, col].set_title(name, fontsize=11)
    axes[0, col].axis("off")

    axes[1, col].imshow(aug_mask, cmap="gray", vmin=0, vmax=1)
    axes[1, col].axis("off")

axes[0, 0].set_ylabel("Imagen", fontsize=11, rotation=0, labelpad=40)
axes[1, 0].set_ylabel("Máscara", fontsize=11, rotation=0, labelpad=40)

# Nota: en entrenamiento real las transformaciones se aplican con p=0.5 (geometricas)
# y p=0.3 (brillo/contraste). Aqui se fuerzan con p=1.0 para visualizar el efecto.


plt.tight_layout()
save_path = "/content/drive/MyDrive/sugarcane/diagrama-aumento-datos.png"
plt.savefig(save_path, dpi=200, bbox_inches="tight")
plt.show()
print(f"Figura guardada en: {save_path}")

"""# Matriz de confusión + Accuracy/Precision/Recall/F1 (val y test)

"""

def metrics_set(subset, dataset, image_processor, model, device, set_name):
    tp = fp = fn = tn = 0
    for idx in tqdm(range(len(subset)), desc=f"Métricas {set_name}"):
        img_path = dataset.samples[subset.indices[idx]][0]
        mask_path = dataset.samples[subset.indices[idx]][1]

        img_bgr = cv2.imread(img_path)
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

        inputs = image_processor(images=img_rgb, return_tensors="pt").to(device)
        with torch.no_grad():
            logits = model(pixel_values=inputs["pixel_values"]).logits

        logits_up = torch.nn.functional.interpolate(
            logits, size=img_rgb.shape[:2], mode="bilinear", align_corners=False
        )
        pred = logits_up.argmax(dim=1).squeeze(0).cpu().numpy()

        gt_bgr = cv2.imread(mask_path)
        gt_rgb = cv2.cvtColor(gt_bgr, cv2.COLOR_BGR2RGB)
        gt_class = mask_rgb_to_class(gt_rgb)   # 1 = caña, 0 = background

        tp += int(((pred == 1) & (gt_class == 1)).sum())
        fp += int(((pred == 1) & (gt_class == 0)).sum())
        fn += int(((pred == 0) & (gt_class == 1)).sum())
        tn += int(((pred == 0) & (gt_class == 0)).sum())

    total = tp + tn + fp + fn
    accuracy  = (tp + tn) / total
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    print(f"\n===== {set_name} =====")
    print("Matriz de confusión (filas = real, columnas = predicho):")
    print(f"            pred. bg      pred. caña")
    print(f"real bg       {tn:>9}     {fp:>9}")
    print(f"real caña     {fn:>9}     {tp:>9}")
    print(f"  Accuracy : {accuracy:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall   : {recall:.4f}")
    print(f"  F1-score : {f1:.4f}")

    return dict(accuracy=accuracy, precision=precision, recall=recall, f1=f1,
                tp=tp, fp=fp, fn=fn, tn=tn)

val_m  = metrics_set(val_raw,  dataset, image_processor, model, device, "VALIDACIÓN")
test_m = metrics_set(test_raw, dataset, image_processor, model, device, "PRUEBA")

print("\n===== RESUMEN =====")
print(f"Val  -> Acc {val_m['accuracy']:.4f} | Prec {val_m['precision']:.4f} | Rec {val_m['recall']:.4f} | F1 {val_m['f1']:.4f}")
print(f"Test -> Acc {test_m['accuracy']:.4f} | Prec {test_m['precision']:.4f} | Rec {test_m['recall']:.4f} | F1 {test_m['f1']:.4f}")
